name: promote
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:        
      - v5.*
jobs:
  build-and-promote:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PRACTICE_TOKEN_MAY_23 }}
      NPM_TOKEN: ${{ secrets.NPM_PRACTICE_TOKEN_MAY_23 }}
    steps:
      - uses: actions/checkout@v2
      - name: Build for promotion
        run: yarn build
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Manual publish
        run: |
          npm version $GITHUB_REF_NAME
          npm publish --tag latest
