name: release
on:
  push:
    branches:
      - v5
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PRACTICE_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_PRACTICE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build my exercise
        run: yarn build
      - name: Release to NPM
        run: npx semantic-release@19.0.5

