name: release
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PRACTICE_ACTIONS_SECRET }}
      NPM_TOKEN: ${{ secrets.NPM_PRACTICE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build my exercise
        run: yarn build
      - name: Release to NPM
        run: npx semantic-release@17.4.3

